AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable
  Exclude:
    - log/**/*
    - tmp/**/*
    - bin/**/*
    - node_modules/**/*
    - db/data_schema.rb
    - db/schema.rb
    - db/migrate/*

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/**/*.rb

Naming/VariableNumber:
  Enabled: false
