version: "1.0"
services:
  web:
    image: mempage/be
    ports:
      - 3000:3000
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    command: server --console-address :9001 /data
networks:
  default:
    name: mempage-network

