version: "1.0"
services:
  backend:
    build: ./
    ports:
      - 3000:3000
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    volumes:
      - './tmp/s3:/data'
    command: server --console-address :9001 /data
networks:
  default:
    name: mempage-network
