default: &default
  adapter: postgresql
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: postgres
  password: postgres123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mempage-dev

test:
  <<: *default
  database: mempage-test

production:
  <<: *default
  database: mempage
