minio: &minio
  service: S3
  access_key_id: "admin"
  secret_access_key: "adminadmin"
  region: "eu-central-1"
  endpoint: "http://<%= ENV.fetch('MINIO_HOST') %>:9000"
  force_path_style: true

development:
  <<: *minio
  bucket: "mempage-dev-bucket"

test:
  <<: *minio
  bucket: "mempage-test-bucket"

amazon:
  service: S3
  access_key_id: ""
  secret_access_key: ""
  bucket: ""
  region: "" # e.g. 'us-east-1'
